# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6129e655feae734fbbc0c63a20d52c3a8f62f7613edd15f3b5343587e44cdcb88d2b3d6984be4ab7568e485f99443d653014d73352b56675a72d4bd1ae860e65

test:
  secret_key_base: 528ae6999d7093dfa16f8ee11de87bd6805aa610b4c90094669b907d2085e6cfa4e926065311be75c668def439d08373bb5dd9aa338fd790b63dfd840fa1df9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
